language: python

dist: xenial
sudo: required

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.6
      - python3.7
      - python3.8
      - python3.9
      - pypy

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: always