language: python

dist: xenial

addons:
  apt:
    packages:
      - python3.5
      - python3.6
      - python3.7
      - python3.8
      - python3.9
      - pypy
      - python3-distutils

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: always