os: linux
dist: xenial
language: python
python:
  - python3.6
  - python3.7
  - python3.8
  - python3.9


install:
  - pip install tox

script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$PATH:~/.cargo/bin
  - tox

notifications:
  email:
    on_success: never
    on_failure: always